Inc7
HAGIT4/go-middle pull request #12
Opened 2022-01-13 17:07 UTC by HAGIT4

2022-01-13 20:54 UTC, lugingf requested changes
набросал комментов :)

2022-01-13 20:54 UTC, lugingf commented on cmd/agent/main.go
> +type Config struct {
Давай конфиг унесем в отдельный пакет может?

2022-01-13 20:54 UTC, lugingf commented on cmd/server/main.go
> +type Config struct {
И тут тоже

2022-01-13 20:54 UTC, lugingf commented on cmd/server/main.go
> +	cfg := &Config{}
Давай всю работу с конфигами не в мэине делать. В мэине будем дергать какой-нибудь `initConfig()` и все, получать готовый конфиг

2022-01-13 20:54 UTC, lugingf commented on internal/server/api/router.go
> +		contentHeader := c.Request.Header.Get("Content-Type")
а давай все эти проверки и логику уберем на уровень конкретного хэндлера. А в роутере будет чистенько и просто имя метода отдаем, которым будем обрабатывать запрос? И здесь и ниже тоже

2022-01-13 20:54 UTC, lugingf commented on internal/server/api/router.go
> +		case metricTypeGauge:
Бизнес логику даже не на уровень хэндлера, а еще глубже. Спрятать под какой-нибудь структурой `MetricServer{}`
Получится в роутере - тольео методы
В хэндлере - работа с http, прием, валидация, оборачивание ответа
В Сервисе - бизнес логика

2022-01-16 13:44 UTC, HAGIT4 commented on cmd/agent/main.go
> +type Config struct {
Вынес в отдельный файл

2022-01-16 13:44 UTC, HAGIT4 commented on cmd/server/main.go
> +type Config struct {
И тут тоже

2022-01-16 13:44 UTC, HAGIT4 commented on cmd/server/main.go
> +	cfg := &Config{}
Done

2022-01-16 13:45 UTC, HAGIT4 commented on internal/server/api/router.go
> +		contentHeader := c.Request.Header.Get("Content-Type")
Вынес хендлеры в отдельный файл

2022-01-16 13:51 UTC, HAGIT4 commented on internal/server/api/router.go
> +		case metricTypeGauge:
Не очень понял, где тут бизнес логика, тут в зависимости от резолв-параметров составляется правильный запрос в сервис
В любом случае, унес в отдельный файл

2022-01-16 18:49 UTC, lugingf commented on internal/agent/agent.go
> +func (a *agent) SendMetricsJSON(data *agentData, pollCount int64) (err error) {
Я смотрю на эти два метода (этот и `SendMetrics`) и прям ощущение, что их можно было бы "подсушить" и сделать одним методом, если вынести отдельно в какие нибудь `prepareData(type)` и `prepareHeaders(type)` отличающиеся части.
Но оставлю это как типа задание со звездочкой

2022-01-16 18:50 UTC, lugingf approved these changes
Принято

2022-02-07 12:29 UTC, merged