Inc13
HAGIT4/go-middle pull request #19
Opened 2022-02-06 08:35 UTC by HAGIT4

2022-02-07 10:51 UTC, lugingf commented
@HAGIT4 Я не знаю почему я не заметил этого раньше.
Сделай пожалуйста merge в main всех инкрементов, который я заапрувил (спринты 1 и 2)

2022-02-07 12:30 UTC, HAGIT4 commented
> @HAGIT4 Я не знаю почему я не заметил этого раньше. Сделай пожалуйста merge в main всех инкрементов, который я заапрувил (спринты 1 и 2)

done

2022-02-07 14:26 UTC, lugingf requested changes
Все хорошо, один коммент оставил

2022-02-07 14:26 UTC, lugingf commented on internal/server/storage/postgresstorage/update.go
> +			_, err = tx.Exec(ctx, "updateGauge", metric.MetricID, metric.GaugeValue)
Можем вынести exec из цикла? Собрать statement и потом одной пачкой все выполнить? Да, в рамках транзакции, но все равно много походов в БД получается

2022-02-07 20:11 UTC, HAGIT4 commented on internal/server/storage/postgresstorage/update.go
> +			_, err = tx.Exec(ctx, "updateGauge", metric.MetricID, metric.GaugeValue)
Вынес создание statement в цикл, exec за цикл

2022-02-09 07:00 UTC, lugingf approved these changes

2022-02-12 15:57 UTC, merged